title: Baybayani
description: >-
  Baybayani is a word puzzle adventure game that aims to teach players Baybayin
  and promote Filipino language.
social_link: twitter
social_username: broccolini
github_repo: athena
github_username: broccolini
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /baybayani
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
